default: test

build:
    ./gradlew build

test:
    ./gradlew test

acceptance-cuke:
    ./gradlew acceptanceCuke || true
    quiq --report-cuke
    open build/reports/tests/acceptance/cucumber/quiq-report.html

dist:
    ./gradlew shadowJar

run *ARGS:
    ./gradlew run --args="{{ARGS}}"
